name: "Go tests"

env:
  GO_BUILD_TAGS: "ce"
  GOPROXY: ${{ secrets.GOPROXY }}

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  go_tests:
    name: Go tests
    runs-on: [self-hosted, regular]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run Go tests
        shell: bash
        run: |
          basedir=$(pwd)
          failed='false'
          # for i in $(find . -type f -name go.mod);do
            dir=. # $(echo $i | sed 's/[a-z_A-Z0-9-]*_test.go$//')
            cd $basedir/$dir
            # check all editions
            for edition in $GO_BUILD_TAGS ;do
              echo "Running tests in $dir (edition: $edition)"
              go test -v -tags $edition ./...
              if [ $? -ne 0 ]; then
                echo "Tests failed in $dir (edition: $edition)"
                failed='true'
              fi
            done
          # done
          if [ $failed == 'true' ]; then
            exit 1
          fi
